version: '3.8'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
