global:
  scrape_interval: 15s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'flask_app'
  #   static_configs:
  #     - targets: ['flask_app:5000']
  #       metrics_path: '/metrics'

  # - job_name: 'express_app'
  #   static_configs:
  #     - targets: ['express_app:3001']
  #       metrics_path: '/metrics'